services:
  alb:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - web
      - api
    command: |
      sh -c "sh -s <<'EOF' cat > /etc/nginx/conf.d/default.conf <<'EON'
      server {
        listen 80;

        location / {
          proxy_pass http://web:80;
        }

        location /api {
          proxy_pass http://api:80;
        }
    }
    EON
    nginx -g 'daemon off;'
    EOF"
